components:
  examples:
    patch-user-example:
      summary: Example patch user
      value:
        createDate: '{{UNIQUE_REFERENCE}}'
        dateOfBirth: '{{ISO_TIMESTAMP}}'
        email: alotta.rotta@gmail.com
        emailVerified: true
        firstName: '{{MY_VAR_NAME}}'
        id: 1
        lastName: '{{MY_VAR_LAST_NAME}}'
  schemas:
    User:
      description: ''
      properties:
        createDate:
          description: The date that the user was created.
          format: date
          type: string
        dateOfBirth:
          format: date
          type: string
        email:
          format: email
          type: string
        emailVerified:
          description: Set to true if the user's email has been verified.
          type: boolean
        firstName:
          type: string
        id:
          description: Unique identifier for the given user.
          type: integer
        lastName:
          type: string
      required:
      - id
      - firstName
      - lastName
      - email
      - emailVerified
      title: User
      type: object
info:
  description: Sample API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: BasicExample
  version: '1.0'
openapi: 3.0.0
paths:
  /users/{userId}:
    patch:
      description: Update User Info
      operationId: patch-users-userId
      parameters:
      - description: Unique identifier of the user
        in: path
        name: userId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            examples:
              patch-user:
                $ref: '#/components/examples/patch-user-example'
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              examples:
                Get User Alice Smith (json):
                  value:
                    dateOfBirth: '1997-10-31'
                    email: alice.smith@gmail.com
                    emailVerified: true
                    firstName: Alice
                    id: 142
                    lastName: Smith
                    signUpDate: '2019-08-24'
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              examples:
                Get User Alice Smith (xml):
                  value:
                    dateOfBirth: '1997-10-31'
                    email: alice.smith@gmail.com
                    emailVerified: true
                    firstName: Alice
                    id: 143
                    lastName: Smith
                    signUpDate: '2019-08-24'
              schema:
                $ref: '#/components/schemas/User'
          description: User Found
        '404':
          description: User Not Found
      summary: Patch User
      tags:
      - basic
servers:
- description: dev server
  url: http://localhost:5001
- description: test server
  url: http://localhost:5001
tags:
- description: Basic tag
  name: basic
